version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    volumes:
      - ./frontend:/frontend
      - ./backend/data:/app/data
    environment:
      - HOST=0.0.0.0
      - PORT=8088
    restart: always
